### ISSUE TITLE
static pages don't contain any content

### ISSUE THREAD

**Issue by janiek** [NetCoreTemplates/vuetify-nuxt#1]
Thanks for publishing this template. Really love vue js and .net core as a combo and this comes in really handy. The only thing I don't get to work is that the generated static pages don't contain any content. It contains the source code like a non SSR-SPA. Am I forgetting something or is this still a bug?

**Comment by mythz** [comment]
It doesn't support Nuxt SSR, only Nuxt.js SPA Mode, see discussion thread in the Customer Forums: https://forums.servicestack.net/t/vuetify-nuxt-with-ssr/5252
